### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Toms0n** [robertjoaca1/carceahookv2#1]
Hello, i see you use csgosimple base for make your rage cheat 
i try to implement your local animfix for my csgosimple base and idk why m_bClientSideAnimation  break my thirdperson bunnyhop etc u know fix for that?

I see many threads on uc about it and i dont find solution for that

**Comment by robertjoaca1** [comment]
no idea mby hook clientsideanimation

**Comment by ghost** [comment]
hook brain.dll.mp4 animation not sure
